export { FrameByFrameError } from './core/errors.js';
export { createFrameByFrame } from './core/public-controller.js';
export { createTimeline } from './mapping/timeline.js';

export type {
  AxisName,
  ElementReference,
  Easing,
  EasingFunction,
  EasingName,
  FrameByFrameAxesConfig,
  FrameByFrameAxisConfig,
  FrameByFrameAxisOverride,
  FrameByFrameAxisState,
  FrameByFrameBindingConfig,
  FrameByFrameBindingEvent,
  FrameByFrameBindingOverride,
  FrameByFrameBindingState,
  FrameByFrameBreakpointChangeEvent,
  FrameByFrameBreakpointConfig,
  FrameByFrameBreakpointOverride,
  FrameByFrameController,
  FrameByFrameErrorCode,
  FrameByFrameErrorDetails,
  FrameByFrameErrorInfo,
  FrameByFrameErrorOptions,
  FrameByFrameEventMap,
  FrameByFrameFrameEvent,
  FrameByFrameLoadedMetadataEvent,
  FrameByFrameLoadProgressEvent,
  FrameByFrameOptions,
  FrameByFrameState,
  FrameByFrameStatus,
  FrameByFrameSeekRequestEvent,
  FrameByFrameUpdateEvent,
  FrameByFrameUpdateReason,
  FrameConfig,
  ScrollSource,
  ScrollSourceReference,
  ScrollUnit,
  MediaCrossOrigin,
  RendererType,
  ReducedMotionBehavior,
  Timeline,
  TimelineOptions,
  TimelinePhase,
  TimelineResolution,
  TimelineSegment,
  VideoClipConfig,
  VideoLoadState,
  VideoLoadProgress,
  VideoLoadingConfig,
  VideoLoadingTrigger,
  VideoPreload,
  VideoRendererConfig,
  VideoSeekConfig,
  VideoSourceConfig,
} from './types.js';
